### ISSUE TITLE
The periodic global noise

### ISSUE THREAD

**Issue by ZhouQianang** [Lynn0306/DVS-Voltmeter#6]
Hello, great job, and thank you for your open-source work. I have found that the simulator periodically produces global noise in actual use. Is this due to my data? There is no such phenomenon when I have very little data (for example, only 10 images, like in the office example). However, when I have slightly more data (20 images), this problem occurs.
![捕获](https://user-images.githubusercontent.com/49708236/231929505-2b119421-f582-4abb-95d4-1b5f34f0e586.JPG)

**Comment by OliveMY** [comment]
Thank you for your interest in our work and sorry for the late reply. The periodic global noise is probably the result of our settings about noise events caused by "leakage current", especially when the scene moves really slow and events are supposed to be sparse. This phenomenon is reasonable in the current simulator setting but hardly observed in the real data for multiple reasons. We are currently working on this part and will update the simulator ASAP.
My suggestion now is to use high-frame-rate videos as input or interpolate the frames to create one before using the simulator, which might alleviate the problem.

**Comment by ZhouQianang** [comment]
> Thank you for your interest in our work and sorry for the late reply. The periodic global noise is probably the result of our settings about noise events caused by "leakage current", especially when the scene moves really slow and events are supposed to be sparse. This phenomenon is reasonable in the current simulator setting but hardly observed in the real data for multiple reasons. We are currently working on this part and will update the simulator ASAP. My suggestion now is to use high-frame-rate videos as input or interpolate the frames to create one before using the simulator, which might alleviate the problem.

Thanks for your reply! Please do not close this issue. I am currently experimenting with new data and parameter settings, and I want to share any new issues or results here."

**Comment by ZhouQianang** [comment]
After replacing the video frame interpolation model, the problem has been greatly alleviated. Thank you for your work.
![github](https://user-images.githubusercontent.com/49708236/233833482-73c115ef-09ea-4b23-88f6-5d5b527d4a40.JPG)

**Comment by OliveMY** [comment]
Thank you for your interest and feedback. If any other problem is encountered, please don't hesitate to open a new issue.
