### ISSUE TITLE
Problem in Long Video Sequence Emulation

### ISSUE THREAD

**Issue by Les1a** [Lynn0306/DVS-Voltmeter#8]
I want to get an emulated event stream of a long video sequence, but the memory space required is beyond the limitations of my device. So, may I ask that is there any difference between the event stream obtained by splicing the event stream after emulating it in segments and emulating it directly?

**Comment by OliveMY** [comment]
Thanks for your interest in our work. The short answer is YES, because the delta_vd_res in the EventSim object (in src/simulator.py) stands for the "residual voltage" of the sensor. If you don't want to keep the simulation same to reading the whole video into memory, maybe it is a good idea to tweak the simulation process a bit to fit in your application. (Read a slice -> event simulation without deleting the EventSim object -> Read next slice ...)

**Comment by Les1a** [comment]
Thank you very much for your advice and explanations! Your expertise and support are very instrumental and helpful.
